arr = [1, 2.5, "Three", true];
console.log(arr.length);
console.log(arr[0]);
console.log(arr);
arr.push(4);
console.log(arr);
arr.pop();
arr.unshift(5);
console.log(arr);
arr.shift();
console.log(arr);
a = arr.indexOf("Three");
console.log(a);
b = arr.slice(0, 2);
console.log(b);
arr.splice(1, 1);
console.log(arr);
c = arr.concat([4, 5]);
console.log(c);
d = arr.reverse();
console.log(d);
