a=input()
print("hi",a)
age=int(input("Enter an age:"))
salary=float(input("Enter ur salary:"))
work=bool(input())
print("your age is",age,"and salary is",salary,"working or not?", work)
print(type(a))
print(type(age))
print(type(salary))
print(type(work))